spring.application.name=cinema-tickets

ticket-service.max-ticket-count=25
ticket-service.ticket-prices[ADULT]=25.99
ticket-service.ticket-prices[CHILD]=17.50
ticket-service.ticket-prices[INFANT]=0
ticket-service.seats-required[ADULT]=1
ticket-service.seats-required[CHILD]=1
ticket-service.seats-required[INFANT]=0

payment-service.protocol=http
payment-service.hostname=payment.local.uk
payment-service.port=8444
payment-service.url=${payment-service.protocol}://${payment-service.hostname}:${payment-service.port}

reservation-service.protocol=http
reservation-service.hostname=reservation.local.uk
reservation-service.port=8444
reservation-service.url=${reservation-service.protocol}://${reservation-service.hostname}:${reservation-service.port}
